name: Test
on:
  workflow_dispatch:

permissions:
      contents: write         

jobs:
  build-and-deploy-stage:
    name: 'Build Artifacts and Deploy to STAGE'
    runs-on: 'ubuntu-latest'
    environment: 'STAGE'
    steps: 
      - name: Encode Variable to Base64
        id: encode
        run: |
          ENCODED=$(echo '${{ secrets.GCP_SA_KEY }}' | base64)
          echo "Encoded Variable: $ENCODED"
          echo 'GCP_SA_KEY_ENCODED<<EOF' >> $GITHUB_ENV
          echo "$ENCODED" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Delete GAE versions
        uses: vijayp23/delete-gae-version-action@1.0.0
        with:
          service-account: ${{ env.GCP_SA_KEY_ENCODED }}
          project-id: ${{ vars.GCP_PROJECT_ID }}
          service-name: 'default'
          retain-versions: 0
          debug: false


  
